### ISSUE TITLE
Issues in section 4

### ISSUE THREAD

**Issue by clayrat** [jyp/organ#2]
Here are the problems (and some solutions) I've encountered when porting section 4 (together with the end-paper implementations) to Idris:
* In `scanSnk'`: linear `a` is obtained from splitting `Cons`, hence both `next` and `y` are linear too, as they are obtained from `f z a`. The problem is then that `next` is passed through non-linear `z` in `scanSrc` back to `scanSnk'` where it can be dropped. I don't have a solution for this.
 * The signatures for folds that work for me are:
```
foldSrc' :: (b -> a -o b) -> b -o Src a -o NN b
foldSnk'' :: (b -o a -o b) -> b -o N b -o Snk' a
foldSnk' :: (b -> a -o b) -> b -> N b -o Snk a
```
Here, linear `a` which is deconstructed from `Cons` in `foldSnk''` gets passed to `f` and the linear result is passed to `foldSrc'`, so it should accept its outer `b` linearly. Since that `b` is passed back to `foldSnk''` it should also accept a outer `b` linearly. Now this linear `b` is again passed to `f`, so the first argument of `f` here should also be linear. At this point Idris' typechecker is satisfied, though the resulting asymmetry across the 3 functions looks a bit weird to me.
* `toListSnk'` should have the signature `N [a] -o Snk' a`, otherwise in `toList` we are passing a linear `k` to a non-linear function. (Technically, the `List` data structure returned here and in `toList` should itself be internally linear as well, to be allowed prepending the linear `x` obtained from `Cons`)
* `unlinesSnk'` requires `:` to be linear, since it accepts the linear `Char` `c`. Apparently this then requires the signature to be changed to `String -o Snk' String -> Snk' Char`, and `reverse` be linear as well. I've achieved this through some coercions, but in general linear versions of functions on primitives look a bit weird to me.
* The lambdas `a -o Maybe b` in `filterSrc` and `filterSnk` should not be linear themselves (i.e., corresponding signatures should start with `(a -o Maybe b) -> ...`) since they get passed to `filterSnk'` where it can be dropped.
* `tee'` should have the signature `(a -o (b, c)) -> Src a -o Sink b -> Src c` since it gets passed a linear `xs` as `Src` in `collapseSnk'`. `collapseSnk` should then be relaxed to `(a -o (b,c)) -> Snk b -> Snk c -o Snk a`. Alternatively, `collapseSnk` could be left as is - then `tee'` needs to be strengthened to `(a -o (b, c)) -> Src a -o Sink b -o Src c`.
* Unfortunately, the entire parser example in 4.4 seems ill-typed. The problem starts from the very last line where linear `x` obtained from deconstructing `Cons` is passed to non-linear `f` (here we should also technically use a linear version of `Maybe`). The version of `P.Sym` where the `Maybe` argument is linear however breaks `weave` and `<|>`. The linearity then infects the signature of `scan`, making it `P s a -o Snk' a -o Src s -o Eff`. This requires `p0` in `parse` to be linear as well, which translates to `Parser s a = P (forall res. (a -> P s res) -o P s res)`. This then breaks all instances for `Parser`. I think it also requires the `Parser s a` argument to `parse` be linear as well, at which point I feel lost :)

**Comment by jyp** [comment]
> In scanSnk': linear a is obtained from splitting Cons, hence both next and y are linear too, as they are obtained from f z a. The problem is then that next is passed through non-linear z in scanSrc back to scanSnk' where it can be dropped. I don't have a solution for this.

I forgot to mark `b` as Bang'ed (! operator in LL --- `Unrestricted` in our Linear Haskell paper)

> The signatures for folds that work for me are:
> foldSrc' :: (b -> a -o b) -> b -o Src a -o NN b
> foldSnk'' :: (b -o a -o b) -> b -o N b -o Snk' a
> foldSnk' :: (b -> a -o b) -> b -> N b -o Snk a
> Here, linear a which is deconstructed from Cons in foldSnk'' gets passed to f and the linear result is passed to foldSrc', so it should accept its outer b linearly. Since that b is passed back to foldSnk'' it should also accept a outer b linearly. Now this linear b is again passed to f, so the first argument of f here should also be linear. At this point Idris' typechecker is satisfied, though the resulting asymmetry across the 3 functions looks a bit weird to me.

I really intended `b` to be bang'ed here too.

> toListSnk' should have the signature N [a] -o Snk' a, otherwise in toList we are passing a linear k to a non-linear function. (Technically, the List data structure returned here and in toList should itself be internally linear as well, to be allowed prepending the linear x obtained from Cons)

Agreed.

> unlinesSnk' requires : to be linear, since it accepts the linear Char c. Apparently this then requires the signature to be changed to String -o Snk' String -> Snk' Char, and reverse be linear as well. I've achieved this through some coercions, but in general linear versions of functions on primitives like looks a bit weird to me.

`reverse` should definitely be linear, as it conserves the list contents. However I believe that the signature should be `unlinesSnk' :: String -> Snk' String ⊸ Snk' Char`


> The lambdas a -o Maybe b in filterSrc and filterSnk should not be linear themselves (i.e., corresponding signatures should start with (a -o Maybe b) -> ...) since they get passed to filterSnk' where it can be dropped.

Yes indeed.

> tee' should have the signature (a -o (b, c)) -> Src a -o Sink b -> Src c since it gets passed a linear xs as Src in collapseSnk'. collapseSnk should then be relaxed to (a -o (b,c)) -> Snk b -> Snk c -o Snk a. Alternatively, collapseSnk could be left as is - then tee' needs to be strengthened to (a -o (b, c)) -> Src a -o Sink b -o Src c.

I really intended:
 `tee' :: (a ⊸ (b, c)) -> Src a ⊸ Sink b ⊸ Src c`


> Unfortunately, the entire parser example in 4.4 seems ill-typed. The problem starts from the very last line where linear x obtained from deconstructing Cons is passed to non-linear f (here we should also technically use a linear version of Maybe). The version of f where the Maybe argument is linear however breaks weave and <|>. The linearity then infects the signature of scan, making P s a -o Snk' a -o Src s -o Eff. This requires p0 in parse to be linear as well, which breaks all instances for Parser. I think it also requires the Parser s a argument to parse be linear as well, at which point I feel lost :)

Here I really intended symbols (s) to be duplicable. This is generally
the case in a real parser. The easy way to approximate that is to Bang
them.

An upcoming patch will address your comments.

Thanks a bunch for this valuable feedback!
